name: Permissions
main: com.nijikokun.bukkit.Permissions.Permissions
version: 2.7
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: >
             The joe.to fake Permissions.